// Generated by https://quicktype.io
package types

// 分析器
type Analyzer struct {
	Baidu    string `json:"baidu"`
	Google   string `json:"google"`
	GoogleAd string `json:"google-ad"`
}

func (a *Analyzer) SetAnalyzer(b string, g string, ad string) {
	a.Baidu = b
	a.Google = g
	a.GoogleAd = ad
}
