// Generated by https://quicktype.io
package types

// 分析器
type Analyzer struct {
	Baidu  string `json:"baidu"`
	Google string `json:"google"`
}

func (a *Analyzer) SetAnalyzer(b string, g string) {
	a.Baidu = b
	a.Google = g
}
