// Generated by https://quicktype.io
package types

type Gitalk struct {
	ClientID     string   `json:"client_id"`
	ClientSecret string   `json:"client_secret"`
	Repo         string   `json:"repo"`
	Owner        string   `json:"owner"`
	Admin        string   `json:"admin"`
	Id           string   `json:"id"`
	Labels       []string `json:"labels"`
}
