// Generated by https://quicktype.io
package types

type Gitalk struct {
	ClientID     string   `json:"client_id"`
	ClientSecret string   `json:"client_secret"`
	Repo         string   `json:"repo"`
	Owner        string   `json:"owner"`
	Id           string   `json:"id"`
	Admin        []string `json:"admin"`
	Labels       []string `json:"labels"`
}

func (g *Gitalk) SetGitalk(clientID string, clientSecret string, repo string, owner string, admin []string, labels []string) {
	g.ClientID = clientID
	g.ClientSecret = clientSecret
	g.Repo = repo
	g.Owner = owner
	g.Admin = admin
	g.Labels = labels
}
