// Generated by https://quicktype.io
package types

type Listener struct {
	Open bool   `json:"open"`
	Host string `json:"host"`
	Cert Cert   `json:"cert"`
}

type Cert struct {
	CertFile string `json:"cert_file"`
	KeyFile  string `json:"key_file"`
}

func (g *Listener) SetListener(open bool, host string, cert Cert) {
	g.Open = open
	g.Host = host
	g.Cert = cert
}
